# Generated by Django 5.0.3 on 2024-03-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_login', '0002_alter_userinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='authenticatedDevices',
        ),
    ]
